{
 "title": "carte",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ID_aeroport",
    "query": "SELECT DISTINCT _id FROM airportsint ORDER BY _id"
   },
   { "name": "query0", "label": "nom_aeroport", "query": "SELECT name from airportsint" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Aéroports et fréquences des vols ✈️\n"
   }
  },
  {
   "title": "Timestamp des données",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "airdata",
     "rawSql": "SELECT MAX(created_at) FROM airportsint LIMIT 50 "
    }
   ]
  },
  {
   "title": "Nombre de vols",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "airdata",
     "rawSql": " SELECT \n        SUM(CAST(value AS numeric)) AS total_value\n    FROM frequencies"
    }
   ]
  },
  {
   "title": "Pays avec le plus de vols par jour",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "airdata",
     "rawSql": "\nSELECT \n    ai.country,\n    SUM(f_sum.total_value) AS total_value_country\nFROM (\n    SELECT \n        airport_id, \n        SUM(CAST(value AS numeric)) AS total_value\n    FROM frequencies\n    GROUP BY airport_id\n) AS f_sum\nJOIN airportsint ai\n  ON f_sum.airport_id = ai._id\nGROUP BY ai.country\nORDER BY total_value_country DESC;"
    }
   ]
  },
  {
   "title": "HeatMap du nombre de vol par jour pour chaque aéroport",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 10, "x": 12, "y": 3 },
   "targets": [
    {
     "dataset": "airdata",
     "rawSql": "SELECT \n    ai._id, \n    ai.name, \n    f_sum.total_value,\n    (ai.geometry::json->'coordinates')->>1 AS latitude,\n    (ai.geometry::json->'coordinates')->>0 AS longitude\nFROM (\n    SELECT \n        airport_id, \n        SUM(CAST(value AS numeric)) AS total_value\n    FROM frequencies\n    GROUP BY airport_id\n) AS f_sum\nJOIN airportsint ai\n  ON f_sum.airport_id = ai._id;"
    }
   ]
  },
  {
   "title": "TOP 15 des aéroports avec le plus de vols/ jour",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "airdata",
     "rawSql": "\nSELECT \n    ai.name, \n    f_sum.total_value\nFROM (\n    SELECT \n        airport_id, \n        SUM(CAST(value AS numeric)) AS total_value\n    FROM frequencies\n    GROUP BY airport_id\n) AS f_sum\nJOIN airportsint ai\n  ON f_sum.airport_id = ai._id\n  ORDER BY f_sum.total_value DESC"
    }
   ]
  }
 ]
}