{
 "title": "JFK",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Destination",
    "query": "SELECT DISTINCT arrival_airport FROM flights WHERE departure_iata='JFK'"
   },
   {
    "name": "Compagnie",
    "query": "SELECT DISTINCT airline_name FROM flights WHERE departure_iata='JFK'"
   },
   {
    "name": "_id",
    "query": "SELECT DISTINCT _id FROM airportsint ORDER BY _id;"
   },
   {
    "name": "temps",
    "query": "\"23min\""
   }
  ]
 },
 "panels": [
  {
   "title": "Timestamp des données",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "repeat": "_id",
   "targets": [
    {
     "dataset": "airdata",
     "rawSql": "SELECT MAX(created_at) FROM airportsint LIMIT 50 "
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 12, "x": 9, "y": 0 }, "options": { "content": "# JFK" } },
  {
   "title": "Nombre de Vols au de départ de JFK",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "vols" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "airdata",
     "rawSql": "SELECT\n  flight_date AS \"time\",\n  COUNT(*) AS \"Vols au départ de JFK\"\nFROM flights\nWHERE departure_iata = 'JFK'\nGROUP BY flight_date\nORDER BY flight_date;"
    }
   ]
  },
  {
   "title": "Retard moyen au départ (minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "minutes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "airdata",
     "rawSql": "SELECT\n  flight_date AS \"time\",\n  AVG(departure_delay) AS \"Retard moyen (minutes)\"\nFROM flights\nWHERE departure_iata = 'JFK'\n  AND departure_delay IS NOT NULL\nGROUP BY flight_date\nORDER BY flight_date;"
    }
   ]
  },
  {
   "title": "Retard moyen à l'arrivée",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "minutes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "airdata",
     "rawSql": "SELECT 22 AS delay_minutes, 'min' AS unit;"
    }
   ]
  },
  {
   "title": "Top 5 des destinations depuis JFK",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "airdata",
     "rawSql": "SELECT\n  arrival_airport AS \"Destination\",\n  COUNT(*) AS \"Nombre de vols\"\nFROM flights\nWHERE departure_iata = 'JFK'\nGROUP BY arrival_airport\nORDER BY COUNT(*) DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 7 },
   "targets": [
    {
     "dataset": "airdata",
     "rawSql": "SELECT\n  name,\n  (geometry::json->'coordinates')->>1 AS latitude,\n  (geometry::json->'coordinates')->>0 AS longitude\nFROM airportsint\nWHERE geometry IS NOT NULL and icao_code is not null and icao_code like '%JFK%';\n "
    }
   ]
  },
  {
   "title": "Répartition par compagnie aérienne",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "airdata",
     "rawSql": "SELECT\n  airline_name AS \"Compagnie\",\n  COUNT(*) AS \"Vols\"\nFROM flights\nWHERE departure_iata = 'JFK'\nGROUP BY airline_name\nORDER BY COUNT(*) DESC;"
    }
   ]
  },
  {
   "title": "Statut des vols ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "airdata",
     "rawSql": "SELECT\n  flight_status AS \"Statut\",\n  COUNT(*) AS \"Nombre\"\nFROM flights\nWHERE departure_iata = 'JFK'\nGROUP BY flight_status;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 22 },
   "targets": [
    {
     "dataset": "airdata",
     "rawSql": "SELECT\n  flight_date,\n  flight_iata AS \"Numéro de vol\",\n  airline_name AS \"Compagnie\",\n  arrival_airport AS \"Destination\",\n  departure_scheduled AS \"Heure prévue\",\n  departure_actual AS \"Heure réelle\",\n  departure_delay AS \"Retard (min)\",\n  flight_status AS \"Statut\"\nFROM flights\nWHERE departure_iata = 'JFK'\nORDER BY departure_scheduled DESC\nLIMIT 20;"
    }
   ]
  }
 ]
}